export const ADD_PROFILES = "ADD_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
